# Generated by Django 5.2 on 2025-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('source_lang', models.CharField(default='en', max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_text', 'target_lang'], name='translator__source__fdb8b2_idx')],
                'unique_together': {('source_text', 'source_lang', 'target_lang')},
            },
        ),
    ]
